apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: tensorflow-gpu-quay 
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
spec:
  template:
    spec:
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
      - name: xray-chest-data
        persistentVolumeClaim:
          claimName: xray-chest-data
          readOnly: true
      - name: workspace
        persistentVolumeClaim:
          claimName: jh-workspace
      containers:
        - name: tensorflow-gpu
          image: quay.io/alegros/tensorflow-gpu:py3.8-cuda-11.4.2 
          volumeMounts:
          - name: xray-chest-data
            mountPath: /opt/app-root/src/data
          - name: workspace
            mountPath: /opt/app-root/src/notebooks
          imagePullPolicy: Always
          workingDir: /opt/app-root/src
          env:
            - name: NOTEBOOK_ARGS
              value: |
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/test-odh/tensorflow-gpu
          ports:
            - name: notebook-port
              containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: "8"
              memory: 16Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "16"
              memory: 32Gi
              nvidia.com/gpu: "1"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /notebook/test-odh/tensorflow-gpu/api
              port: notebook-port
